name: H100
num_sms: 132
tensor_throughput_per_sm: 4096
simt_throughput_per_sm: 256
dram_bw_bytes_per_cycle: 1851.851851851852
l2_bw_bytes_per_cycle: 9000
smem_bw_bytes_per_cycle_per_sm: 256
clock_mhz: 1620
